// MIT License — Luna AI Web | Built by Ravikiran (github.com/R22-b)
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = require('docx');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const pptx = require('pptxgenjs');
const ExcelJS = require('exceljs');
const { chat } = require('./brain-manager');

async function generateContent(topic, instructions, pages) {
  const prompt = `You are a professional document writer. Create structured content for a document.
Topic: ${topic}
Instructions: ${instructions}
Pages: approximately ${pages}

Respond ONLY with valid JSON in this exact format:
{
  "title": "Document Title",
  "sections": [
    {
      "heading": "Section Heading",
      "content": "Main paragraph content here...",
      "bullets": ["Point 1", "Point 2", "Point 3"]
    }
  ],
  "summary": "Brief summary of the document"
}`;

  const result = await chat([{ role: 'user', content: prompt }], 'chat');
  try {
    const jsonMatch = result.response.match(/\{[\s\S]*\}/);
    return JSON.parse(jsonMatch[0]);
  } catch {
    return {
      title: topic,
      sections: [{ heading: 'Overview', content: result.response, bullets: [] }],
      summary: result.response.substring(0, 200),
    };
  }
}

async function generateWord(topic, instructions, pages) {
  const content = await generateContent(topic, instructions, pages);
  const children = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: content.title, bold: true, size: 48, font: 'Calibri' })],
      spacing: { after: 400 },
    }),
  ];
  for (const section of content.sections) {
    children.push(
      new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: section.heading, bold: true, size: 28, color: '2E4057' })] }),
      new Paragraph({ children: [new TextRun({ text: section.content, size: 22 })], spacing: { after: 200 } }),
      ...section.bullets.map(b =>
        new Paragraph({ children: [new TextRun({ text: `• ${b}`, size: 22 })], indent: { left: 360 } })
      ),
    );
  }
  children.push(
    new Paragraph({ children: [new TextRun({ text: '' })] }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: 'Generated by Luna AI Web | github.com/R22-b', size: 18, color: '888888', italics: true })],
    }),
  );
  const doc = new Document({ sections: [{ properties: {}, children }] });
  return await Packer.toBuffer(doc);
}

async function generatePDF(topic, instructions, pages) {
  const content = await generateContent(topic, instructions, pages);
  const pdfSafe = value => String(value ?? '').replace(/[^\x00-\x7F]/g, '');
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const addPage = () => {
    const page = pdfDoc.addPage([595, 842]);
    page.drawRectangle({ x: 0, y: 0, width: 595, height: 842, color: rgb(0.06, 0.06, 0.12) });
    page.drawText(pdfSafe('Luna AI Web | github.com/R22-b'), { x: 50, y: 20, size: 8, font, color: rgb(0.5, 0.5, 0.5) });
    return page;
  };

  let page = addPage();
  let y = 780;

  // Title
  page.drawText(pdfSafe(content.title), { x: 50, y, size: 24, font: boldFont, color: rgb(0.49, 0.23, 0.93) });
  y -= 50;

  for (const section of content.sections) {
    if (y < 100) { page = addPage(); y = 780; }
    page.drawText(pdfSafe(section.heading), { x: 50, y, size: 16, font: boldFont, color: rgb(0.04, 0.71, 0.83) });
    y -= 25;
    const words = section.content.split(' ');
    let line = '';
    for (const word of words) {
      if ((line + word).length > 80) {
        if (y < 100) { page = addPage(); y = 780; }
        page.drawText(pdfSafe(line.trim()), { x: 50, y, size: 11, font, color: rgb(0.9, 0.9, 0.9) });
        y -= 16; line = '';
      }
      line += word + ' ';
    }
    if (line.trim()) { page.drawText(pdfSafe(line.trim()), { x: 50, y, size: 11, font, color: rgb(0.9, 0.9, 0.9) }); y -= 16; }
    for (const bullet of section.bullets) {
      if (y < 100) { page = addPage(); y = 780; }
      page.drawText(pdfSafe(`- ${bullet}`), { x: 70, y, size: 11, font, color: rgb(0.8, 0.8, 0.8) });
      y -= 18;
    }
    y -= 20;
  }
  return await pdfDoc.save();
}

async function generatePPT(topic, instructions, pages) {
  const content = await generateContent(topic, instructions, pages);
  const prs = new pptx();
  prs.layout = 'LAYOUT_WIDE';
  prs.defineLayout({ name: 'LAYOUT_WIDE', width: 13.33, height: 7.5 });

  // Title slide
  const titleSlide = prs.addSlide();
  titleSlide.background = { color: '0a0a0f' };
  titleSlide.addText(content.title, { x: 1, y: 2.5, w: 11, h: 1.5, fontSize: 40, bold: true, color: '7c3aed', align: 'center' });
  titleSlide.addText('Generated by Luna AI Web | github.com/R22-b', { x: 1, y: 6.5, w: 11, h: 0.5, fontSize: 14, color: '06b6d4', align: 'center' });

  for (const section of content.sections) {
    const slide = prs.addSlide();
    slide.background = { color: '0a0a0f' };
    slide.addText(section.heading, { x: 0.5, y: 0.3, w: 12, h: 1, fontSize: 28, bold: true, color: '7c3aed' });
    slide.addText(section.content, { x: 0.5, y: 1.5, w: 12, h: 2, fontSize: 16, color: 'e2e8f0', wrap: true });
    if (section.bullets.length) {
      const bulletText = section.bullets.map(b => ({ text: `• ${b}`, options: { color: '94a3b8', fontSize: 15 } }));
      slide.addText(bulletText, { x: 0.5, y: 3.8, w: 12, h: 3, lineSpacingMultiple: 1.5 });
    }
    slide.addText('Luna AI Web', { x: 11, y: 7, w: 2, h: 0.4, fontSize: 10, color: '475569' });
  }

  return await prs.write({ outputType: 'nodebuffer' });
}

async function generateExcel(topic, instructions) {
  const content = await generateContent(topic, instructions, 2);
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Luna AI Web | github.com/R22-b';
  const sheet = workbook.addWorksheet(topic.substring(0, 30));

  sheet.addRow([content.title]).font = { bold: true, size: 16, color: { argb: 'FF7c3aed' } };
  sheet.addRow([]);

  for (const section of content.sections) {
    const headingRow = sheet.addRow([section.heading]);
    headingRow.font = { bold: true, size: 13, color: { argb: 'FF06b6d4' } };
    headingRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1a1a2e' } };
    sheet.addRow([section.content]);
    for (const bullet of section.bullets) {
      sheet.addRow([`• ${bullet}`]);
    }
    sheet.addRow([]);
  }
  sheet.addRow(['Generated by Luna AI Web | github.com/R22-b']).font = { italic: true, color: { argb: 'FF888888' } };
  sheet.getColumn(1).width = 80;

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

module.exports = { generateWord, generatePDF, generatePPT, generateExcel };
