import { useState } from 'react';
import { Download, Wand2, Image } from 'lucide-react';
import toast from 'react-hot-toast';
import { imageAPI } from '../utils/api';
import { LoadingSpinner, CacheIndicator, PageHeader } from '../components/shared';

const STYLES = [
  { id: 'realistic', label: '📷 Realistic',    desc: 'Photorealistic 8K' },
  { id: 'anime',     label: '🌸 Anime',        desc: 'Studio Ghibli style' },
  { id: 'neon',      label: '💜 Neon',         desc: 'Cyberpunk neon glow' },
  { id: 'cyberpunk', label: '🌆 Cyberpunk',    desc: 'Blade Runner aesthetic' },
  { id: 'oil_painting', label: '🖼️ Oil Paint', desc: 'Classical art' },
  { id: 'sketch',    label: '✏️ Sketch',       desc: 'Pencil drawing' },
  { id: 'watercolor',label: '🎨 Watercolor',   desc: 'Soft painted' },
  { id: 'fantasy',   label: '🧙 Fantasy',      desc: 'Epic digital art' },
];

export default function ImagePage() {
  const [prompt, setPrompt] = useState('');
  const [style, setStyle] = useState('realistic');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState([]);

  const generate = async () => {
    if (!prompt.trim()) return toast.error('Enter a prompt first!');
    setLoading(true);
    try {
      const { data } = await imageAPI.generate(prompt, style, 1024, 1024);
      setResult(data);
      setHistory(prev => [data, ...prev].slice(0, 8));
      toast.success(`Generated by ${data.provider}!`);
    } catch (err) { toast.error(err.message); }
    finally { setLoading(false); }
  };

  const download = () => {
    const a = document.createElement('a');
    a.href = result.imageData;
    a.download = `luna_${Date.now()}.jpg`;
    a.click();
  };

  return (
    <div className="max-w-3xl mx-auto">
      <PageHeader icon="🎨" title="Image Generation" subtitle="AI-powered images — completely free via Pollinations & HuggingFace" />

      {/* Style selector */}
      <div className="grid grid-cols-4 gap-2 mb-4">
        {STYLES.map(s => (
          <button key={s.id} onClick={() => setStyle(s.id)}
            className={`p-2.5 rounded-lg border text-left transition-all ${style === s.id ? 'border-primary bg-primary/10' : 'border-border bg-surface2 hover:border-slate-500'}`}>
            <div className="text-xs font-medium text-white">{s.label}</div>
            <div className="text-xs text-slate-500">{s.desc}</div>
          </button>
        ))}
      </div>

      {/* Prompt input */}
      <div className="flex gap-2 mb-6">
        <input value={prompt} onChange={e => setPrompt(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && generate()}
          placeholder="Describe your image... (e.g. a neon tiger in cyberpunk city)"
          className="flex-1 bg-surface2 border border-border rounded-xl px-4 py-3 text-white placeholder-slate-500 focus:border-primary outline-none text-sm" />
        <button onClick={generate} disabled={loading}
          className="px-5 py-3 bg-primary rounded-xl text-white font-medium hover:bg-primary/90 disabled:opacity-40 transition-all flex items-center gap-2">
          <Wand2 size={16} />
          {loading ? 'Generating...' : 'Generate'}
        </button>
      </div>

      {/* Result */}
      {loading && <LoadingSpinner text="Generating your image with AI magic... ✨" />}
      {!loading && result && (
        <div className="luna-card overflow-hidden mb-6">
          <img src={result.imageData} alt={result.prompt} className="w-full object-cover" />
          <div className="p-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-xs text-slate-400">{result.provider}</span>
              <CacheIndicator fromCache={result.fromCache} />
            </div>
            <button onClick={download}
              className="flex items-center gap-2 px-3 py-1.5 bg-success/20 text-success rounded-lg text-sm hover:bg-success/30 transition-colors">
              <Download size={14} /> Download
            </button>
          </div>
        </div>
      )}

      {/* History */}
      {history.length > 1 && (
        <div>
          <h3 className="text-sm font-medium text-slate-400 mb-3">Recent Generations</h3>
          <div className="grid grid-cols-4 gap-2">
            {history.slice(1).map((img, i) => (
              <img key={i} src={img.imageData} alt="" onClick={() => setResult(img)}
                className="rounded-lg aspect-square object-cover cursor-pointer hover:ring-2 hover:ring-primary transition-all" />
            ))}
          </div>
        </div>
      )}
      <p className="text-center text-slate-600 text-xs mt-6">Luna AI Web Preview | github.com/R22-b</p>
    </div>
  );
}
